package br.tche.ucpel.bd2.view;


import br.tche.ucpel.bd2.bean.Disciplina;
import br.tche.ucpel.bd2.dao.DisciplinaDAO;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 * Classe responsável pelo desenho da tela de cadastro do Departamento.
 * <br/>
 * São tratados eventos de lostFocus (perda do foco) no campo txtCodigo, os
 * eventos de acionamento de botões e o duplo click na tabela.
 *
 * @author mertins
 */
public class FormDisciplina extends javax.swing.JInternalFrame {

    private JFrame mdi;

    /**
     * Creates new form FormDepartamento
     *
     * @param mdi MDI principal.
     */
    public FormDisciplina(JFrame mdi) {
        this.mdi = mdi;
        initComponents();
        this.atualizaLista();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCod = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        btExcluir = new javax.swing.JButton();
        btAtualizar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbDisciplina = new javax.swing.JTable();
        btLimpar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtTurma = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCargaHoraria = new javax.swing.JTextField();
        txtNumAlunos = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btSalvar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastro de Disciplinas");

        jLabel1.setText("Codigo");

        jLabel2.setText("Nome");

        txtCod.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodFocusLost(evt);
            }
        });
        txtCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodActionPerformed(evt);
            }
        });

        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btAtualizar.setText("Atualizar");
        btAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarActionPerformed(evt);
            }
        });

        tbDisciplina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nome", "Turma", "Nº Alunos", "Carga Horaria"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbDisciplina.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbDisciplina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDisciplinaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbDisciplina);

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        jLabel4.setText("Turma");

        jLabel5.setText("Carga horaria");

        txtNumAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumAlunosActionPerformed(evt);
            }
        });

        jLabel6.setText("Nº Alunos");

        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCargaHoraria))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btAtualizar)
                        .addGap(18, 18, 18)
                        .addComponent(btLimpar)
                        .addGap(18, 18, 18)
                        .addComponent(btExcluir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtCargaHoraria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtNumAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btLimpar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btExcluir)
                        .addComponent(btAtualizar))
                    .addComponent(btSalvar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed
    this.atualizaLista();
}//GEN-LAST:event_btAtualizarActionPerformed

private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed

    try {
        int codigo = this.transformaString(this.txtCod.getText());
        if (codigo > 0) {
            Disciplina disciplina = new Disciplina(codigo);
            DisciplinaDAO disDAO = new DisciplinaDAO(MDISistema.getConexao());
            disDAO.delete(disciplina);
            this.limpaTela();
            this.atualizaLista();
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this.mdi, String.format("Erro ao excluir Disciplina:%s", ex.getMessage()), "Erro", JOptionPane.ERROR_MESSAGE);
        Logger.getLogger(FormDisciplina.class.getName()).log(Level.WARNING, "Erro ao excluir Disciplina", ex);
    }
    this.atualizaLista();
}//GEN-LAST:event_btExcluirActionPerformed

private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
    this.limpaTela();
}//GEN-LAST:event_btLimparActionPerformed

private void tbDisciplinaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDisciplinaMouseClicked
// TODO add your handling code here:
    if (evt.getClickCount() > 1) {
        JTable obj = (JTable) evt.getComponent();
        int linha = obj.getSelectedRow();
        Integer Codigo = (Integer) obj.getModel().getValueAt(linha, 0);
        Disciplina dis = new Disciplina(Codigo);
        this.preencheTela(dis);
    }
}//GEN-LAST:event_tbDisciplinaMouseClicked

private void txtCodFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodFocusLost
// TODO add your handling code here:
    /* int cod = this.intCampoTelas(this.txtMatricula.getText());
    if (cod > 0) {
        Departamento dept = new Departamento(cod);
        boolean ret = this.preencheTela(dept);
        if (!ret) {
            JOptionPane.showMessageDialog(this.mdi, "Código do Departamento não existe no sistema", "Aviso", JOptionPane.WARNING_MESSAGE);
            this.txtMatricula.requestFocusInWindow();
        }
    }*/
}//GEN-LAST:event_txtCodFocusLost

    private void txtCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodActionPerformed

    private int transformaString(String valor) {
        int ret = -1;
        try {
            ret = Integer.parseInt(valor);
        } catch (NumberFormatException ex) {

        }
        return ret;
    }

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        try {
            // TODO add your handling code here:
            Disciplina func = new Disciplina();

            func.setNome(this.txtNome.getText());
            func.setCod(this.transformaString(this.txtCod.getText()));
            func.setTurma(this.transformaString(this.txtTurma.getText()));
            func.setNumAlunos(this.transformaString(this.txtNumAlunos.getText()));
            func.setCargaHoraria(this.transformaString(this.txtCargaHoraria.getText()));

            DisciplinaDAO funcDao = new DisciplinaDAO(MDISistema.getConexao());
            if (func.getCod() != -1) {
                // A matrícula é um valor válido, salva no banco de dados
                funcDao.create(func);
            } else {
                System.out.println("Cod retornou -1");
            }

            JOptionPane.showMessageDialog(this.mdi, "Registro Salvo");
            this.limpaTela();
            this.atualizaLista();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this.mdi, String.format("Erro ao gravar Disciplina:%s", ex.getMessage()), "Erro", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(FormDisciplina.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btSalvarActionPerformed

    private void txtNumAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumAlunosActionPerformed

    }//GEN-LAST:event_txtNumAlunosActionPerformed

    /**
     * Método auxiliar para atualizar a JTable com os dados do Aluno
     */
    private void atualizaLista() {
        try {
            DisciplinaDAO disciplinaDAO = new DisciplinaDAO(MDISistema.getConexao());
            List<Disciplina> lista = disciplinaDAO.listaTodos();
            DefaultTableModel dtm = (DefaultTableModel) this.tbDisciplina.getModel();
            dtm.setRowCount(0);
            for (Disciplina func : lista) {
                dtm.addRow(new Object[]{func.getCod(), func.getNome(), func.getTurma(), func.getNumAlunos(), func.getCargaHoraria()});
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this.mdi, String.format("Erro :%s", ex.getMessage()), "Erro", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(FormDisciplina.class.getName()).log(Level.WARNING, "Erro", ex);
        }
    }

    /**
     * Método auxiliar para limpar os campos da tela.
     */
    private void limpaTela() {
        this.txtCod.setEnabled(true);
        this.txtCod.setText(null);
        this.txtNome.setText(null);
        this.txtNumAlunos.setText(null);
        this.txtTurma.setText(null);
        this.txtCargaHoraria.setText(null);
    }

    private boolean preencheTela(Disciplina disciplina) {
        boolean ret = false;
        try {
            DisciplinaDAO disciplinaDAO = new DisciplinaDAO(MDISistema.getConexao());
            disciplina = disciplinaDAO.retrieve(disciplina);
            if (disciplina!= null && disciplina.getCod() > 0) {
                this.txtCod.setText(Integer.toString(disciplina.getCod()));
                this.txtCod.setEnabled(false);
                this.txtNome.setText(disciplina.getNome());
                this.txtTurma.setText(Integer.toString(disciplina.getTurma()));
                this.txtNumAlunos.setText(Integer.toString(disciplina.getNumAlunos()));
                this.txtCargaHoraria.setText(Integer.toString(disciplina.getCargaHoraria()));
                
                ret = true;
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this.mdi, String.format("Não foi possível carregar Disciplina: %s", ex.getMessage()), "Erro", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(FormDepartamento.class.getName()).log(Level.SEVERE, null, ex);
        }
        return ret;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAtualizar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tbDisciplina;
    private javax.swing.JTextField txtCargaHoraria;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumAlunos;
    private javax.swing.JTextField txtTurma;
    // End of variables declaration//GEN-END:variables
}
